### https://adventofcode.com/2022/day/5


### Part 1
### After the rearrangement procedure completes, what crate ends up on top of each stack?

In [2]:
import math
import numpy as np
# from pathlib import Path
# import os
# from os.path import join, getsize

In [15]:
# Formatting the instructions.

puzzle = np.loadtxt('day5/puzzle.txt', dtype=str, skiprows=10)
print(puzzle[0:5])
print(puzzle.shape)
puzzle = puzzle[:, [1,3,5]]
puzzle = puzzle.astype('int32')
print(puzzle[0:5])

[['move' '8' 'from' '7' 'to' '1']
 ['move' '9' 'from' '1' 'to' '9']
 ['move' '4' 'from' '5' 'to' '4']
 ['move' '4' 'from' '6' 'to' '1']
 ['move' '3' 'from' '8' 'to' '5']]
(503, 6)
[[8 7 1]
 [9 1 9]
 [4 5 4]
 [4 6 1]
 [3 8 5]]


In [45]:
# Crate positions with the first character being the top of the stack.

crates = ['RCH', 'FSLHJB', 'QTJHDMR', 'JBZHRGS', 'BCDTZFPR', 'GCHT', 'LWPBZVNS', 'CGQJR', 'SFPHRTDL']

In [46]:
# Cycle through the instructions reversing the order of the crates picked up.

for i in range(puzzle.shape[0]):
    move_num, from_stack, to_stack = puzzle[i]  # e.g. 8 7 1
    to_move = crates[from_stack - 1][:move_num][::-1]  # e.g. SNVZBPWL
    crates[from_stack - 1] = crates[from_stack - 1][move_num:]  # e.g. empty string ''
    crates[to_stack - 1] = to_move + crates[to_stack - 1]  # e.g. SNVZBPWLRCH

print(crates)
to_print = ''
for i in range(9):
    to_print += crates[i][0]

print(to_print)

['SFHCTGHFQVM', 'HCPZBJR', 'QDZDRJ', 'W', 'SGJ', 'R', 'BT', 'DTRTJSRLLGPZNCHCSHHBRFPB', 'L']
SHQWSRBDL


### Part 2

In [47]:
# Cycle through the instructions without reversing the order of the crates picked up.

crates = ['RCH', 'FSLHJB', 'QTJHDMR', 'JBZHRGS', 'BCDTZFPR', 'GCHT', 'LWPBZVNS', 'CGQJR', 'SFPHRTDL']

for i in range(puzzle.shape[0]):
    move_num, from_stack, to_stack = puzzle[i]
    to_move = crates[from_stack - 1][:move_num]
    crates[from_stack - 1] = crates[from_stack - 1][move_num:]
    crates[to_stack - 1] = to_move + crates[to_stack - 1]

print(crates)
to_print = ''
for i in range(9):
    to_print += crates[i][0]

print(to_print)


['CQBTJTRHMDS', 'DZCNTPB', 'TWRHRS', 'Q', 'ZZF', 'H', 'BG', 'RRFPJHFVSLRHLDJPCJCHLBGG', 'S']
CDTQZHBRS
